import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Pacifico } from "next/font/google";
import "./globals.css";
import BackgroundBlob from "@/components/BackgroundBlob";
import AIStatus from "@/components/AIStatus";
import { Analytics } from "@vercel/analytics/react";

const useAI = process.env.NEXT_PUBLIC_USE_AI === "true";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "InterviewBot",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${pacifico.variable} antialiased min-h-screen`}
      >
        <div className="relative gradient-bg min-h-screen w-full flex flex-col flex-1 overflow-hidden">
          <BackgroundBlob />

          {/* Page content */}
          <div className="z-10 flex flex-1 flex-col justify-center items-center px-4">
            {children}
          </div>

          {!useAI && <AIStatus />}

          <footer className="z-50 flex items-center gap-2 absolute bottom-4 right-4 text-sm text-black/40 dark:text-white/30">
            <span className="select-none pointer-events-none">© 2025 · Made by Diba</span>
            <a 
              className="text-black/20 dark:text-white/15 hover:text-black/40 dark:hover:text-white/30 transition cursor-pointer" 
              href="https://www.linkedin.com/in/diba-malikzadeh-74700736a"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="LinkedIn Profile"
            >
              <svg
                className="w-4 h-4"
                fill="currentColor"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 67 67"
              >
                <path d="M50.837 48.137V36.425c0-6.275-3.35-9.195-7.816-9.195-3.604 0-5.219 1.983-6.119 3.374V27.71h-6.79c.09 1.917 0 20.427 0 20.427h6.79V36.729c0-.609.044-1.219.224-1.655.49-1.22 1.607-2.483 3.482-2.483 2.458 0 3.44 1.873 3.44 4.618v10.929h6.789zM22.959 24.922c2.367 0 3.842-1.57 3.842-3.531-.044-2.003-1.475-3.528-3.797-3.528s-3.841 1.524-3.841 3.528c0 1.961 1.474 3.531 3.753 3.531h.043zM34 64C17.432 64 4 50.568 4 34 4 17.431 17.432 4 34 4s30 13.431 30 30c0 16.568-13.432 30-30 30zm-7.646-15.863V27.71h-6.789v20.427h6.789z" />
              </svg>
            </a>
          </footer>
        </div>
        <Analytics />
      </body>
    </html>
  );
}
